server:
  port: 8080
logging:
  config: file:./config/logback-spring.xml
spring:
  datasource:
    url: jdbc:h2:mem:devsudatabase
    username: devsu
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
devsu:
  diaryAmountLimit: 1000