CREATE TABLE CLIENTS (ID BIGINT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(255), GENDER VARCHAR(255), AGE INTEGER, PERSONAL_ID VARCHAR(255), ADDRESS VARCHAR(255), PHONE VARCHAR(255), PASSWORD VARCHAR(255), STATE BOOLEAN, UNIQUE(PERSONAL_ID));
CREATE TABLE ACCOUNTS(ID BIGINT AUTO_INCREMENT PRIMARY KEY,BALANCE NUMERIC(19,2),NUMBER VARCHAR(255),STATE BOOLEAN,TYPE VARCHAR(255),CLIENT_ID BIGINT,UNIQUE(NUMBER),FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(ID));
CREATE TABLE TRANSACTIONS (ID BIGINT AUTO_INCREMENT PRIMARY KEY,AMOUNT NUMERIC(19,2),DATE_TIME TIMESTAMP,INITIAL_BALANCE NUMERIC(19,2),FINAL_BALANCE NUMERIC(19,2), ACCOUNT_ID BIGINT,FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ID));

SELECT CURRENT_TIMESTAMP;
INSERT INTO CLIENTS (NAME, GENDER, AGE, PERSONAL_ID, ADDRESS, PHONE, PASSWORD, STATE) VALUES ('Jose Lema', 'MALE', 25, '354981984', 'Otavalo sn y principal', '09825785', '1234', TRUE);
INSERT INTO CLIENTS (NAME, GENDER, AGE, PERSONAL_ID, ADDRESS, PHONE, PASSWORD, STATE) VALUES ('Marianela Montalvo', 'FEMALE', 25, '354981985', 'Amazonas y NNUU', '097548965', '5678', TRUE);
INSERT INTO CLIENTS (NAME, GENDER, AGE, PERSONAL_ID, ADDRESS, PHONE, PASSWORD, STATE) VALUES ('Juan Osorio', 'MALE', 25, '354981986', '13 junio y Equinoccial', '098874587', '1245', TRUE);

INSERT INTO ACCOUNTS (CLIENT_ID, NUMBER, TYPE, BALANCE, STATE) VALUES (1, '478758', 'AHORRO', 2000, TRUE);
INSERT INTO ACCOUNTS (CLIENT_ID, NUMBER, TYPE, BALANCE, STATE) VALUES (2, '225487', 'CORRIENTE', 100, TRUE);
INSERT INTO ACCOUNTS (CLIENT_ID, NUMBER, TYPE, BALANCE, STATE) VALUES (3, '495878', 'AHORRO', 0, TRUE);
INSERT INTO ACCOUNTS (CLIENT_ID, NUMBER, TYPE, BALANCE, STATE) VALUES (2, '496825', 'AHORRO', 540, TRUE);


INSERT INTO TRANSACTIONS (ACCOUNT_ID, DATE_TIME, INITIAL_BALANCE, AMOUNT, FINAL_BALANCE) VALUES (2, PARSEDATETIME('10-02-2022 00:00:00.00', 'dd-MM-yyyy hh:mm:ss.SS'), 100, 600, 700);
INSERT INTO TRANSACTIONS (ACCOUNT_ID, DATE_TIME, INITIAL_BALANCE, AMOUNT, FINAL_BALANCE) VALUES (4, PARSEDATETIME('08-02-2022 00:00:00.00', 'dd-MM-yyyy hh:mm:ss.SS'), 540, -540, 0);

// It might be better to create a trigger
SELECT CURRENT_TIMESTAMP;
UPDATE ACCOUNTS SET BALANCE = 700 WHERE ID = 2;
UPDATE ACCOUNTS SET BALANCE = 0 WHERE ID = 4;

COMMIT;